name: ticktacktoe
description: A mobile game for mobile devices built in Flutter.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.1+4

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

#  audioplayers: ^3.0.0
  cupertino_icons: ^1.0.2
  go_router: ^7.1.1
  logging: ^1.1.0
  provider: ^6.0.2
  shared_preferences: ^2.0.13

  # If you don't need one of the following dependencies,
  # delete the relevant line below, and get rid of any Dart code
  # that references the dependency.
  firebase_core: ^2.7.0  # Needed for Crashlytics below
  firebase_crashlytics: ^3.0.15  # Error reporting
  games_services: ^3.0.1  # Achievements and leaderboards
  google_mobile_ads: ^2.4.0  # Ads
  in_app_purchase: ^3.0.1  # In-app purchases

  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  analysis_defaults:
    path: analysis_defaults
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  test: ^1.19.0

flutter:
  uses-material-design: true

  assets:
    - assets/i18n/
    - assets/images/
    - assets/music/
    - assets/sfx/
    - android/app/src/main/res/mipmap-mdpi/
    - android/app/src/main/res/drawable-v21/
    - android/app/src/main/res/mipmap-xxhdpi/
    - android/app/src/main/res/values/
    - android/app/src/main/res/drawable/
    - android/app/release/
    - android/app/src/main/java/io/
    - android/app/src/main/java/io/flutter/
    - android/app/src/main/java/io/flutter/plugins/
    - android/app/
    - android/app/src/main/kotlin/com/
    - android/app/src/
    - android/app/src/main/kotlin/com/example/
    - android/app/src/main/
    - android/app/src/main/kotlin/com/example/game_template/
    - android/app/src/main/res/
    - android/app/src/main/res/mipmap-hdpi/
    - android/app/src/main/res/mipmap-xxxhdpi/
    - android/app/src/debug/
    - android/app/src/profile/
    - android/app/src/main/res/mipmap-xhdpi/
    - android/app/src/main/java/
    - android/app/src/main/kotlin/
    - android/app/src/main/res/values-night/

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/Permanent_Marker/PermanentMarker-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: assets/Pacifico-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon-adaptive-foreground.png"
