// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY8_ZF3CjT7b5hEsrpddrPmgtcOeLGZqU',
    appId: '1:44586511309:web:b73812bc2de83dfc96b284',
    messagingSenderId: '44586511309',
    projectId: 'tictactoe-27b21',
    authDomain: 'tictactoe-27b21.firebaseapp.com',
    storageBucket: 'tictactoe-27b21.appspot.com',
    measurementId: 'G-DBFT147V1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvEINd-ebbWMB1YpYO8SZjNjVItckYSPs',
    appId: '1:44586511309:android:422ebf139828cfaa96b284',
    messagingSenderId: '44586511309',
    projectId: 'tictactoe-27b21',
    storageBucket: 'tictactoe-27b21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl4W68Am6ExJA51XGsJ2I4D7UDatU95xQ',
    appId: '1:44586511309:ios:f7d779de26a2bb9896b284',
    messagingSenderId: '44586511309',
    projectId: 'tictactoe-27b21',
    storageBucket: 'tictactoe-27b21.appspot.com',
    iosClientId: '44586511309-qaiqdqdq7a7u9u43pdjipk9l7rg2bmgi.apps.googleusercontent.com',
    iosBundleId: 'com.antonov.gameTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl4W68Am6ExJA51XGsJ2I4D7UDatU95xQ',
    appId: '1:44586511309:ios:f7d779de26a2bb9896b284',
    messagingSenderId: '44586511309',
    projectId: 'tictactoe-27b21',
    storageBucket: 'tictactoe-27b21.appspot.com',
    iosClientId: '44586511309-qaiqdqdq7a7u9u43pdjipk9l7rg2bmgi.apps.googleusercontent.com',
    iosBundleId: 'com.antonov.gameTemplate',
  );
}
